RomchyFCC/GitHub-Practice-For-All

links and support/Guides.md
links and support/cheat_sheets.md

Split into markdown and git guides

Split guides

---

index.html

Added my own to the h1 co-creator tag

Added darren name to the list

---

index.html
static/style.css

Also adds a light background to the forkers paragraph so text is visible.

Adds sexiest, most amaze-balls camper of all time.

---

index.html
static/style.css

Adding my own name and putting up a new steampunk neon css styling.
Thanks for doing this woot woot!

Add name and style

---

The Website/style.css

Changed the existing color.
Added one more color.
Change the deg from 90 to 180.

Updated style.css with more colors

---

The Website/index.html
The Website/style.css

Hi, this is my first pull request ever, is this still active?

Added my FCC username

---

The Website/style.css

I added some borders to the div elements per the issue raised by Darren. Hope this is what you wanted. Thanks.

used css to add borders to div elements

---

The Website/style.css

@DarrenfJ  I added linear gradient to  co-creator class, and some padding on .romchy
Great exercise, thanks :)

Added gradient to .co-creator

---

Guides/Git guides.md

I personally took this course to learn the foundations of version control, Git and collaboration on GitHub. I found it very informative, well-structured, and highly engaging.

Add new course to Git guides.md

---

The Website/index.html

sorry I didn't do anything creative, just thought I would contribute :)

added name to index file

---

The Website/script.js

I kept the secret from the example. Let me know if you want to change it.

Added function for secret string

---

The Website/script.js

I changed the secret to something people are more likely to type! ;)  Maybe you could let others change the secret as a first timer issue.

Changed the secret code

---

The Website/index.html
The Website/style.css

Added my name Sheena to the index.html file.

Add myname

---

The Website/style.css

Gave my name some text shadow as the new background made it unreadable. Great to see more people getting involved!

Added text-shadow to my name

---

README.md

Added First Timers Only Tag, issue 46

First timers only

---

The Website/style.css

could i help you organizing some words and colors of this website?! :smile_cat:

modifying colors

---

style.css

Just discovered background-clip: text! Gave Firuz Shoev a  gold effect.

Changed styles for Firuz Shoev

---

style.css

Nice catch! I always forget to check other browsers.

Added a prefix for background-clip in chrome

---

index.html
style.css

Used CSS Grid to make the site super responsive. I had to refactor the html a little to make it work.
Oh yeah, i also changed the styles on that last name. Probably should have done this in a separate PR.
Can undo the changes to ariel leslie if it makes sense to keep the issues separate?

CSS Grid applied to body tag

---

index.html
style.css

CSS Grid wasn't working as intended on my phone( should only be 1 column on small devices ). Finally remembered about this meta tag for mobile. Also cleaned up the commented out CSS.

Added meta tag for mobile devices

---

README.md

Hello @RomchyFCC  and @DarrenfJ 
I have made some changes so the sub-list bullet points is vertically align with first letter of the list item number two.
Hope that is what you expected.

README.md Indenting

---

index.html
style.css

The things I think need to be changed/added:
-  [How to PR](https://github.com/RomchyFCC/GitHub-Practice-For-All/blob/master/README.md#how-to-pr) section: 'How to sync your local repo with the original repo' for details: Add a link to the  'How to sync your local repo part.
- [How to PR](https://github.com/RomchyFCC/GitHub-Practice-For-All/blob/master/README.md#how-to-pr) section: You forgot to add `git add` and `git commit` before the "Push your change to your fork" `git push` step.

Added my name with some style.

---

index.html
style.css

Good place to practice, thank  you!

Add my name

---

contributors.html
index.html
style/contributors.css
style/style.css

I put the new style.css in the style folder. I wasn't sure if it should be top level like index.html?

Renamed style.css to contributors.css

---

index.html
style.css

new contributor

---

contributors.html
style/contributors.css

Added rcat contribution.

---

index.html
style/style.css

Added section elements with headers and linked them in nav. Added smooth scroll-behavior to css.

add section elements

---

style/contributors.css

I just saw that in the class .rcat there was a border property that was wrong. I just changed it to the one I think the user meant.

changed the contributers.css .rcat border-size to border-width

---

contributors.html
index.html
scripts/script.js
style/style.css

I tried my best to make no changes to the other html and css code! Please let me know, if I should make further changes. Thank you!

added nav and noreferrer security on contributors page

---

contributors.html

Updated **contributors.html** by adding my name

add-your-name-#34

---

contributors.html
style/contributors.css

I am new to using Git and Github and I just added my name Matt L as a contributer by adding HTML and CSS with my name to the contributer's page.  
Somebody please respond so that I can confirm that this is working and that I am doing the right thing.  Did I push to the right person?
I was also wondering if I can have permission to do this a second and third time so that I can get more comfortable with the process.  If I do that, I may opt to erase my original change and code a slightly different one.  Would this be OK?
Thanks.
Matt

Matt added as a contributer

---

contributors.html
style/contributors.css

Romchy,
Thanks for giving me permission to do this again.  
I am now trying to add Matt#2 to the master branch (yesterday it was MattL that I pushed and you merged).
Nevertheless, I've encountered the following problems:
1) it says above "x Can't automatically merge" in red when I opened this pull request.  I do not remember seeing this with my first contribution yesterday.  Did I do something wrong?
2) When I forked and cloned today for my instant second contribution, I did not see my contribution from yesterday.  Why?
I synced it as per the instructions, but my yesterday's pushed and merged contributions (MattL) failed to show when I displayed the contributors page in a web browser.
Do you happen to know why?
Did I do something wrong?
Matt

matt#2 being added as a contributer

---

golf-project/index.html

Created the first folders and files necessary for the project.

Let's make a project 0

---

contributors.html
style/contributors.css

Dear @RomchyFCC , I have added my name. Thank you for reviewing.

Modified contributors.md

---

contributors.html
style/contributors.css

Add John Hanna to contributors.html and contributors.css

Add John Hanna to contributors

---

contributors.html
style/contributors.css

I have added my name in "contributors.html" file and also added some css for it.

added my name

---

contributors.html

Added name to Contributors.html

---

contributors.html

Added my information

---

contributors.html
style/contributors.css

this is first time made pull request. thanks you for you're repo!

Adding myname nrs

---

contributors.html

Added my name, "DannyTheDev. To the html and learned that to make a "<a>" class into a bigger size like <h2> you put the h2 around the a class which was a pretty new concept to me. Thank you so much for this

updated contributors.html

---

contributors.html

Funny way to learn to contribute #34

Funny way to learn to contribute

---

contributors.html
style/contributors.css

I'm just a lowly Project Manager trying to learn how to code, tried something with the styling special for Halloween. Let me know what you think and thank you!

Add My Name, Halloween Style

---

contributors.html
style/contributors.css

Sorry I made a mistake when I added my name earlier, this makes it less boring.

Ok! This will fix my name!

---

contributors.html
style/contributors.css

Just adding myself to the contributor page to get started. Going to take a look at some of the real issues and see if there's anything I can help out with

Adding myself on the contributor page

---

README.md
contributors.html
style/contributors.css

Hi @RomchyFCC - thanks so much for creating this! I had a hard time finding a repo to contribute to, but this made it much less daunting to make my first pull request. Anyways, all I did here was add my name to the html and readme.md files along with a bit of css.

Add my name to contributor list

---

README.md

Added name to contributors

---

contributors.html

added name

---

contributors.html

added my name on list as instructed

added me on list

---

contributors.html

Adding pedro to contributors

---

README.md

added as a contributor on list as instructed

update readme, added as contributor

---

contributors.html

Hello, I have added my name to the contributions.

Branchtest

---

contributors.html
style/contributors.css

new-contributor-yoon

---

contributors.html
style/contributors.css

added name to contributers

---

index.html

The project button was one the left side for the mobile version.

mobile version project button set to middle

---

contributors.html
style/contributors.css

Hi I've contributed by adding myself as a contributor!

Added Pan Chee as Contributor

---

contributors.html

Hi, thanks your this nice idea of practicing collaboration working. Pls. take a look and feedback for eventually needed changes. Cheers, Sven

Added my name and inline style

---

contributors.html

Removed one of two links to my account from the contributors page.
More info in #183

Removed one of two link to profile

---

contributors.html
style/contributors.css

Added Name (html+css)
